# Generated by Django 4.0.3 on 2022-05-21 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(verbose_name='Fecha_Nacimiento')),
                ('cc', models.IntegerField(verbose_name='cc')),
                ('departamento', models.CharField(max_length=80, verbose_name='Departamento')),
                ('ciudad', models.CharField(max_length=80, verbose_name='Ciudad')),
                ('phone', models.IntegerField(verbose_name='Phone')),
                ('slug', models.CharField(max_length=150, null=True, unique=True, verbose_name='URL')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='usuarios/pictures')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuenta',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo_Subasta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=20, null=True, verbose_name='categoria')),
                ('marca', models.CharField(max_length=20, null=True, verbose_name='marca')),
                ('modelo', models.CharField(max_length=20, null=True, verbose_name='modelo')),
                ('año', models.IntegerField(null=True, verbose_name='año')),
                ('kilometraje', models.IntegerField(null=True, verbose_name='kilometraje')),
                ('motor', models.CharField(blank=True, max_length=20, null=True, verbose_name='motor')),
                ('cilindraje', models.CharField(blank=True, max_length=20, null=True, verbose_name='cilindraje')),
                ('combustible', models.CharField(max_length=20, null=True, verbose_name='combustible')),
                ('placa', models.CharField(max_length=6, null=True, verbose_name='placa')),
                ('color', models.CharField(max_length=20, null=True, verbose_name='color')),
                ('estado_motor', models.IntegerField(null=True, verbose_name='estado-motor')),
                ('estado_chasis', models.IntegerField(null=True, verbose_name='estado-chasis')),
                ('estado_luces', models.IntegerField(null=True, verbose_name='estado-luces')),
                ('estado_llantas', models.IntegerField(null=True, verbose_name='estado-motor')),
                ('especific_estado', models.CharField(max_length=200, null=True, verbose_name='especific-estado')),
                ('soat', models.CharField(max_length=2, verbose_name='soat')),
                ('fecha_soat', models.CharField(blank=True, max_length=20, null=True, verbose_name='fecha_soat')),
                ('tecno', models.CharField(max_length=2, null=True, verbose_name='tecno')),
                ('fecha_tecno', models.DateField(blank=True, null=True, verbose_name='fecha_tecno')),
                ('propietario', models.CharField(blank=True, max_length=100, null=True, verbose_name='propietario')),
                ('cc_propietario', models.IntegerField(blank=True, null=True, verbose_name='cc-propietario')),
                ('phone_propietario', models.CharField(blank=True, max_length=10, null=True, verbose_name='phone_propietario')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.cuenta')),
            ],
            options={
                'verbose_name': 'Info Vehiculo',
            },
        ),
        migrations.CreateModel(
            name='Foto_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, upload_to=models.CharField(max_length=255))),
                ('cuenta', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.PROTECT, to='usuarios.cuenta')),
                ('vehiculo', models.ForeignKey(max_length=10, on_delete=django.db.models.deletion.CASCADE, to='usuarios.vehiculo_subasta')),
            ],
            options={
                'verbose_name': 'Foto Vehiculo',
            },
        ),
    ]
