# Generated by Django 4.0.3 on 2022-05-21 23:08

from django.db import migrations, models
import usuarios.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foto_vehiculo',
            name='url',
        ),
        migrations.AlterField(
            model_name='foto_vehiculo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=usuarios.models.Foto_Vehiculo.get_upload_to),
        ),
    ]
