# Generated by Django 4.0.3 on 2022-05-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_foto_vehiculo_url_alter_foto_vehiculo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='foto_vehiculo',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
