# Generated by Django 4.0.3 on 2022-04-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subasta',
            name='año',
            field=models.IntegerField(verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='subasta',
            name='kilometraje',
            field=models.IntegerField(verbose_name='kilometraje'),
        ),
    ]
