# Generated by Django 4.0.3 on 2022-04-30 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_subasta_año_alter_subasta_kilometraje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subasta',
            new_name='Vehiculo_Subasta',
        ),
    ]
