# Generated by Django 4.0.3 on 2022-04-30 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_subasta_vehiculo_subasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='cilindraje',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='cilindraje'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='fecha_soat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='fecha_soat'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='fecha_tecno',
            field=models.DateField(blank=True, null=True, verbose_name='fecha_tecno'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='motor',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='motor'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='phone_propietario',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='phone_propietario'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='propietario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='propietario'),
        ),
    ]
