# Generated by Django 4.0.3 on 2022-05-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_vehiculo_subasta_cilindraje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='especific_estado',
            field=models.CharField(max_length=200, null=True, verbose_name='especific-estado'),
        ),
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='estado_chasis',
            field=models.IntegerField(null=True, verbose_name='estado-chasis'),
        ),
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='estado_llantas',
            field=models.IntegerField(null=True, verbose_name='estado-motor'),
        ),
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='estado_luces',
            field=models.IntegerField(null=True, verbose_name='estado-luces'),
        ),
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='estado_motor',
            field=models.IntegerField(null=True, verbose_name='estado-motor'),
        ),
    ]
