# Generated by Django 4.0.3 on 2022-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_vehiculo_subasta_especific_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='año',
            field=models.IntegerField(null=True, verbose_name='año'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='categoria',
            field=models.CharField(max_length=20, null=True, verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='kilometraje',
            field=models.IntegerField(null=True, verbose_name='kilometraje'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='marca',
            field=models.CharField(max_length=20, null=True, verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='modelo',
            field=models.CharField(max_length=20, null=True, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='placa',
            field=models.CharField(max_length=6, null=True, verbose_name='placa'),
        ),
        migrations.AlterField(
            model_name='vehiculo_subasta',
            name='tecno',
            field=models.CharField(max_length=2, null=True, verbose_name='tecno'),
        ),
    ]
