# Generated by Django 4.0.3 on 2022-05-06 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_vehiculo_subasta_año_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo_subasta',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
